on:
  push
jobs:
  LoginDocker:
    - name: Login to GitHub Container Registry
          uses:docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.token }}
